"""Response models for review answers"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Boolean, Enum as SQLEnum
import enum
from sqlalchemy.orm import relationship
from app.database import Base


class ResponseStatus(str, enum.Enum):
    """Status of response"""
    DRAFT = "draft"
    APPROVED = "approved"
    SENT = "sent"
    FAILED = "failed"


class ResponseDraft(Base):
    """Draft response generated by AI"""
    
    __tablename__ = "response_drafts"
    
    id = Column(Integer, primary_key=True, index=True)
    review_id = Column(Integer, ForeignKey("reviews.id"), index=True)
    text = Column(Text)
    variant_number = Column(Integer)  # 1, 2, 3 for 3 variants
    is_selected = Column(Boolean, default=False)
    generated_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<ResponseDraft {self.id}: variant {self.variant_number}>"


class Response(Base):
    """Sent response to review"""
    
    __tablename__ = "responses"
    
    id = Column(Integer, primary_key=True, index=True)
    review_id = Column(Integer, ForeignKey("reviews.id"), index=True)
    draft_id = Column(Integer, ForeignKey("response_drafts.id"), nullable=True)
    text = Column(Text)
    status = Column(SQLEnum(ResponseStatus), default=ResponseStatus.DRAFT, index=True)
    ozon_response_id = Column(String, unique=True, nullable=True, index=True)  # ID returned by Ozon
    created_at = Column(DateTime, default=datetime.utcnow)
    sent_at = Column(DateTime, nullable=True)
    error_message = Column(Text, nullable=True)
    
    def __repr__(self):
        return f"<Response {self.id}: {self.status}>"
